services:
  - type: web
    name: score-forecasting
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --timeout 120"
    plan: free
    autoDeploy: true
